services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: postgresql://postgres:123123@postgres:5432/postgres

    ports:
      - "3000:3000"

    depends_on:
      - postgres